### PR TITLE
Removing hard-coded domains & IPs

### PR DESCRIPTION
**Pull request by giorgos314**
Changing all hard-coded settings in cs-com client and postfix. I've tested these changes locally and everything seems OK.

### CODE REVIEW

**Comment by pparent76** [comment]
2 things:
1°) when doing "IP=$(dig +short $FQDN)" you should make a check that the request did not fail and IP is not void. ( A DNS request can allways fail for a reason or an other).
2°) sed -i request.h -e "s#proxy.omb.one#$FQDN#" seems to me as a duplicated with what you already committed in cs-com, isn't it?

**Comment by giorgos314** [comment]
Oh, yes it is indeed duplicated. I didn't notice that. I will change it and add checks for dig.

**Comment by giorgos314** [comment]
@pparent76 About the duplicated line `sed -i request.h -e "s#proxy.omb.one#$FQDN#"`:

I am doing the final testing of debstrap + proxy (from clean installations). It turns out that the above line, in **cs-com**, causes the testing version of debstrap to crash. 

The reason is the first line of the cs-com script: `include /host/settings.sh`. Because settings.sh doesn't exist in debstrap (but exists in the proxy, that's why the proxy works).

So, what I propose is: 

1) Keep the change here (because `$FQDN` exists in debstrap and proxy doesn't really care about omb-client)

2) Do a small change and remove `sed -i request.h -e "s#proxy.omb.one#$FQDN#"` from cs-com. [I did that here already.](https://github.com/Own-Mailbox/cs-com/commit/35defa16da1420e5991b755e7656ada91c665a73)

Sorry for the mixup, this didn't cause problems earlier as I was pulling the old version of cs-com in debstrap.

**Comment by pparent76** [comment]
you can do this for now.

**Comment by giorgos314** [comment]
Ok great!

**Pull request merged**
