### PR TITLE
Fix docker

### PR DESCRIPTION
**Pull request by dashohoxha**

### CODE REVIEW

**Comment by dashohoxha** [comment]
@pparent76 I am trying to install Own-Mailbox in RaspberryPi3, using Docker.
The steps that I have used are here: https://github.com/dashohoxha/dashohoxha.github.io/blob/master/_org/_posts/2016-10-15-ownmailbox-on-rpi.org

I have improved a bit Docker scripts (and minor modifications on other scripts as well). The iptables still doesn't work, but I will look again at it.

I am getting to the point that I can see "Enter your identification link" on the browser.
How can I find this identification link? If I need such links during the workshop, for the participants, where can I find them?

Thanks,
Dashamir

**Comment by dashohoxha** [comment]
It seems that the problems of iptables come from `ip6tables`. Why not disable ip6 at all and remove all the firewall rules about it? Is it used somewhere?

**Comment by pparent76** [comment]
I initially wanted to disable ipv6 but I did not find a good way to do it safely. How would you like to do it?

Also some people may think that it's a shame we're not compatible with ipv6.

**Comment by pparent76** [comment]
Well actually IPv6 is used, just for a little hack:

Mailpile sends email on port 25 through IP ::1
Tor opens the tor hidden service on port 25 for ip 127.0.0.1
Postfix accepts to relay only emails incoming from ::1 in order to have an open relay on tor.

Well there probably would be other ways to do it, but that's how it was done for now.

**Comment by dashohoxha** [comment]
For disabling IPv6, look at the section "How to turn off IPv6" here: https://wiki.debian.org/DebianIPv6
For the "shame" part, let's be pragmatic. If it's not used and is not needed or necessary, remove it or disable it. Let's be fancy on the future versions of own-mailbox, when we actually need to use it.
Having scripts that don't work because of ip6 is worse than not being fancy.

**Comment by dashohoxha** [comment]
But you say that it is used for a trick, so let's keep it.
If it was possible to change this trick and remove/disable IPv6, it would be better and more secure (in my opinion).

**Comment by dashohoxha** [comment]
The command `modprobe` fails inside the container because it needs more system capabilities (or permissions) to run. This is what causes the failure of the iptables script. If `modprobe ip_tables` is comented out, everything seems to run fine, including ip6tables. So, we don't need to disable it for the time being. We can consider disabling it later.

**Pull request merged**
